spring.application.name=tyzhprogramist

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
#spring.datasource.password=KillMe2070

spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

app.jwt.secret=yDThswjGlUmJPGVNoMj38TZxufR2uBIEQVGsEEbfYdtk7pyGCMMIQiJG69EuzgH2
app.jwt.access-expiration-ms=86400000
app.jwt.refresh-expiration-days=14

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#ACTUATOR & METRICS
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoints.web.exposure.exclude=env,beans
management.endpoints.web.base-path=/actuator
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=tyzhprogramist
management.metrics.distribution.slo.http.server.requests=10ms,50ms,100ms,200ms,500ms,1s,2s
management.metrics.enable.all=true

# ??????? ??? ?????????? ??????????
management.metrics.web.server.request.autotime.enabled=true
management.metrics.web.server.request.autotime.percentiles=0.5,0.9,0.95,0.99